name: Build Nomad for Windows

on:
  push:
    branches:
      - main
      - release/**
  workflow_dispatch:
    inputs:
      build-ref:
        description: 'The git ref to build from'
        type: string
        default: ''
        required: false
      make-prerelease:
        description: "Run prerelease to generate files"
        type: "boolean"
        required: false
        default: true

env:
  PKG_NAME: "nomad"
  GO_TAGS: "release"

jobs:
  get-go-version:
    runs-on: ubuntu-20.04
    outputs:
      go-version: ${{ steps.get-go-version.outputs.go-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.build-ref }}
      - name: Determine Go version
        id: get-go-version
        run: |
          echo "Building with Go $(cat .go-version)"
          echo "go-version=$(cat .go-version)" >> "$GITHUB_OUTPUT"

  get-product-version:
    runs-on: ubuntu-20.04
    outputs:
      product-version: ${{ steps.get-product-version.outputs.product-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.build-ref }}
      - name: get product version
        id: get-product-version
        run: |
          make version
          echo "product-version=$(make version)" >> "$GITHUB_OUTPUT"

  build-windows:
    needs: [get-go-version, get-product-version]
    runs-on: windows-latest
    strategy:
      matrix:
        goarch: ["386", "amd64"]
      fail-fast: true

    name: Go ${{ needs.get-go-version.outputs.go-version }} Windows ${{ matrix.goarch }} build

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.build-ref }}
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ needs.get-go-version.outputs.go-version }}

      - name: Build dependencies
        run: make deps

      - name: Setup node and yarn
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache-dependency-path: "ui/yarn.lock"

      - name: Install Yarn
        run: |
          npm install -g yarn

      - name: Build prerelease
        run: make prerelease
        if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.make-prerelease == 'true' }}

      - name: Build
        env:
          GOOS: windows
          GOARCH: ${{ matrix.goarch }}
          GO_TAGS: ${{ env.GO_TAGS }}
          CGO_ENABLED: 1
        run: |
          go clean -cache
          make pkg/windows_${{ matrix.goarch }}.zip
          mv pkg/windows_${{ matrix.goarch }}.zip ${{ env.PKG_NAME }}_${{ needs.get-product-version.outputs.product-version }}_windows_${{ matrix.goarch }}.zip

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PKG_NAME }}_${{ needs.get-product-version.outputs.product-version }}_windows_${{ matrix.goarch }}.zip
          path: ${{ env.PKG_NAME }}_${{ needs.get-product-version.outputs.product-version }}_windows_${{ matrix.goarch }}.zip

permissions:
  contents: read
  id-token: write
